/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'TLR2'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct tlr_BaseData_t;
struct tlr_MasterTable_t;
struct tlr_Record_t;

/* 298 */
struct tlr_GlobalTable_t
{
  _BYTE gap0[60];
  tlr_BaseData_t *BaseData;
};

/* 48 */
typedef unsigned __int8 BYTE;

/* 299 */
struct tlr_BaseData_t
{
  BYTE gap0[60];
  tlr_MasterTable_t *MasterTable;
  int unk0;
  int unk1;
  _DWORD *stringtable;
};

/* 303 */
struct tlr_TableDesc_t
{
  int unk0;
  int unk1;
  int RecordLength;
  int RecordCount;
  int unk2;
  int unk3;
  int unk4;
  int unk5;
  int unk6;
  int unk7;
  int unk8;
  tlr_Record_t *Records;
  int unk9;
};

/* 302 */
struct tlr_MasterTable_t
{
  tlr_TableDesc_t Tables[320];
};

/* 304 */
struct tlr_Record_t
{
  int unk[2000];
};

